name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    strategy:
      matrix:
        env:
          - name: mcp-auth-proxy-linux-amd64
            os: linux
            arch: amd64
          - name: mcp-auth-proxy-linux-arm64
            os: linux
            arch: arm64
          - name: mcp-auth-proxy-darwin-amd64
            os: darwin
            arch: amd64
          - name: mcp-auth-proxy-darwin-arm64
            os: darwin
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build
        env:
          GOOS: ${{ matrix.env.os }}
          GOARCH: ${{ matrix.env.arch }}
          CGO_ENABLED: 0
        run: go build -o bin/${{ matrix.env.name }} .

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.env.name }}
          path: bin/${{ matrix.env.name }}

      - name: Publish artifacts to release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: github.event_name == 'release'
        run: gh release upload ${{ github.event.release.tag_name }} bin/${{ matrix.env.name }}
